# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.20.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [34]:
# Method 1
a = np.random.random(30)
a = a.reshape((2,3,5))

In [38]:
# Method 2
rg = np.random.default_rng(1)
a = rg.random((2,3,5))

In [54]:
# Method 3
a = np.empty((2,3,5))

#### 4. Print *a*.


In [33]:
# your code here
a

array([[[0.39228095, 0.15915247, 0.1313365 , 0.65688923, 0.6891102 ],
        [0.53788052, 0.15540094, 0.84934207, 0.92288573, 0.65709096],
        [0.79987701, 0.15859526, 0.68867651, 0.44429181, 0.40728968]],

       [[0.17490896, 0.21848039, 0.44080301, 0.52778547, 0.30513887],
        [0.98062662, 0.68660754, 0.49838585, 0.97051879, 0.81594483],
        [0.57600704, 0.55089516, 0.14634598, 0.53159321, 0.0510891 ]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [40]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [41]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [46]:
# your code here
print(f'size of a is: {a.shape}')
print(f'size of b is: {b.shape}')
print(a.shape == b.shape)

size of a is: (2, 3, 5)
size of b is: (5, 2, 3)
False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [47]:
# your answer here
a+b
#no, since they don't have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [62]:
# your code here

c = np.transpose(b, (1, 2, 0))

print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [58]:
# your code/answer here
d = a + c
d
#sicne they have the same shape now

array([[[1.51182162, 1.9504637 , 1.14415961, 1.94864945, 1.31183145],
        [1.42332645, 1.82770259, 1.40919914, 1.54959369, 1.02755911],
        [1.75351311, 1.53814331, 1.32973172, 1.7884287 , 1.30319483]],

       [[1.45349789, 1.1340417 , 1.40311299, 1.20345524, 1.26231334],
        [1.75036467, 1.28040876, 1.48519097, 1.9807372 , 1.96165719],
        [1.72478994, 1.54122686, 1.2768912 , 1.16065201, 1.96992541]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [59]:
# your code/answer here
print(a)
print(d)
#each element in d is equal to the same position of element in a + 1(since each element in c equal to q)

[[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
  [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
  [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]]

 [[0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
  [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]
  [0.72478994 0.54122686 0.2768912  0.16065201 0.96992541]]]
[[[1.51182162 1.9504637  1.14415961 1.94864945 1.31183145]
  [1.42332645 1.82770259 1.40919914 1.54959369 1.02755911]
  [1.75351311 1.53814331 1.32973172 1.7884287  1.30319483]]

 [[1.45349789 1.1340417  1.40311299 1.20345524 1.26231334]
  [1.75036467 1.28040876 1.48519097 1.9807372  1.96165719]
  [1.72478994 1.54122686 1.2768912  1.16065201 1.96992541]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [61]:
# your code here
e = a*c
e

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [63]:
# your code/answer here
print(a)
print(e)
#yes, since number * 1 always eaqual to the number

[[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
  [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
  [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]]

 [[0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
  [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]
  [0.72478994 0.54122686 0.2768912  0.16065201 0.96992541]]]
[[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
  [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
  [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]]

 [[0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
  [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]
  [0.72478994 0.54122686 0.2768912  0.16065201 0.96992541]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [68]:
# your code here
d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(f'max = {d_max}, min = {d_min}, mean ={d_mean}')

max = 1.9807371998012386, min = 1.0275591132430684, mean =1.5135194619749464


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [70]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [82]:
# your code here
#for d1 in d:
#    for d2 in d1:
#        for d3 in d2:
#            for i in range(5):
#                if d_min<d3<d_mean:
#                    
#            for i in len(f3):
#                if d_min<d3<d_mean:

In [85]:
for i1 in range(0,2):
    for i2 in range(0,3):
        for i3 in range(0,5):
            if d_min< d[i1,i2,i3] < d_mean:
                f[i1,i2,i3] = 25
            elif d_mean< d[i1,i2,i3] < d_max: 
                f[i1,i2,i3] = 75
            elif d[i1,i2,i3] == d_mean:
                f[i1,i2,i3] = 50
            elif d[i1,i2,i3] == d_min:
                f[i1,i2,i3] = 0
            else:
                f[i1,i2,i3] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [89]:
# your code here
print(f)

[[[ 25.  75.  25.  75.  25.]
  [ 25.  75.  25.  75.   0.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  25.  25.  25.  25.]
  [ 75.  25.  25. 100.  75.]
  [ 75.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [88]:
# your code here
g = np.empty((2,3,5),str)
for i1 in range(0,2):
    for i2 in range(0,3):
        for i3 in range(0,5):
            if d_min< d[i1,i2,i3] < d_mean:
                g[i1,i2,i3] = 'B'
            elif d_mean< d[i1,i2,i3] < d_max: 
                g[i1,i2,i3] = 'D'
            elif d[i1,i2,i3] == d_mean:
                g[i1,i2,i3] = 'C'
            elif d[i1,i2,i3] == d_min:
                g[i1,i2,i3] = 'A'
            else:
                g[i1,i2,i3] = 'E'
print(g)

[[['B' 'D' 'B' 'D' 'B']
  ['B' 'D' 'B' 'D' 'A']
  ['D' 'D' 'B' 'D' 'B']]

 [['B' 'B' 'B' 'B' 'B']
  ['D' 'B' 'B' 'E' 'D']
  ['D' 'D' 'B' 'B' 'D']]]
